"""Add new features

Revision ID: 9695dcce88f7
Revises: 
Create Date: 2025-11-13 23:29:25.229129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9695dcce88f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=False),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extension_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_expires_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('course', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('total_books_borrowed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_extension_requests', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('library_hours_this_month', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('library_hours_this_year', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('library_hours_this_year')
        batch_op.drop_column('library_hours_this_month')
        batch_op.drop_column('total_extension_requests')
        batch_op.drop_column('total_books_borrowed')
        batch_op.drop_column('course')
        batch_op.drop_column('year')

    with op.batch_alter_table('extension_request', schema=None) as batch_op:
        batch_op.drop_column('status_expires_at')

    op.drop_table('library_session')
    # ### end Alembic commands ###
